services:
  - type: web
    name: job-alerts-flask
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true

cronJobs:
  - name: run-job-alerts
    schedule: "0 10 * * *"  # κάθε μέρα στις 10:00 π.μ.
    command: "python app.py"
