name: Send Job Alerts

# Πότε να τρέχει: χειροκίνητα ή αυτόματα κάθε μέρα στις 10:00 UTC
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 10 * * *'

jobs:
  send-alerts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run alert script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python app.py
