name: Daily Job Alerts

on:
  schedule:
    - cron: '0 10 * * *'  # Κάθε μέρα στις 10:00 το πρωί
  workflow_dispatch:

jobs:
  send-job-alerts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: python app.py
