# .github/workflows/send-job-alerts.yml
name: send-job-alerts

on:
  schedule:
    - cron: '0 10 * * *'   # κάθε μέρα στις 10:00 UTC

jobs:
  fetch-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run job-alert script
        env:
          ADZUNA_APP_ID:  ${{ secrets.ADZUNA_APP_ID }}
          ADZUNA_APP_KEY: ${{ secrets.ADZUNA_APP_KEY }}
          EMAIL_USER:     ${{ secrets.EMAIL_USER }}
          EMAIL_PASS:     ${{ secrets.EMAIL_PASS }}
        run: python app.py
