jobs:
  send-alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check ADZUNA_APP_ID
        run: echo "ADZUNA_APP_ID is: $ADZUNA_APP_ID"
        env:
          ADZUNA_APP_ID: ${{ secrets.ADZUNA_APP_ID }}

      - name: Run alert script
        env:
          ADZUNA_APP_ID:  ${{ secrets.ADZUNA_APP_ID }}
          ADZUNA_APP_KEY: ${{ secrets.ADZUNA_APP_KEY }}
          EMAIL_USER:     ${{ secrets.EMAIL_USER }}
          EMAIL_PASS:     ${{ secrets.EMAIL_PASS }}
        run: python app.py
